=== Open-Attestation/schemas/src/io/tradetrust/invoice/1.0/schema.json
{
  "$id": "https://schemata.openattestation.com/io/tradetrust/certificate-of-origin/1.0",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "Description of data expected for certificate of origin documents",
  "required": ["id"],
  "definitions": {
    "CompanyInfo": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "streetAddress": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "postalCode": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "string"
        }
      }
    }
  },
  "properties": {
    "id": {
      "type": "string"
    },
    "date": {
      "type": "string"
    },
    "customerId": {
      "type": "string"
    },
    "terms": {
      "type": "string"
    },
    "subtotal": {
      "type": "string"
    },
    "tax": {
      "type": "string"
    },
    "taxTotal": {
      "type": "string"
    },
    "total": {
      "type": "string"
    },

    "billFrom": {
      "$ref": "#/definitions/CompanyInfo"
    },

    "billTo": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "company": {
          "$ref": "#/definitions/CompanyInfo"
        },
        "email": {
          "type": "string"
        },
        "postalCode": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "string"
        }
      }
    },

    "billableItems": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "quantity": {
            "type": "string"
          },
          "unitPrice": {
            "type": "string"
          },
          "amount": {
            "type": "string"
          }
        }
      }
    },

    "links": {
      "type": "object",
      "properties": {
        "self": {
          "type": "object",
          "properties": {
            "href": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== Open-Attestation/schemas/src/io/tradetrust/invoice/1.0/invoice-data.json
{
  "billFrom": {
    "name": "User 1",
    "streetAddress": "Street 1",
    "city": "City 1 ",
    "postalCode": "Postal 1",
    "phoneNumber": "Number 1"
  },
  "billTo": {
    "company": {
      "name": "Company 1",
      "streetAddress": "Company Addr 1",
      "city": "Company City 1",
      "postalCode": "Company Postal 1",
      "phoneNumber": "Company Number 1"
    },
    "name": "BillTo 1",
    "email": "Email"
  },
  "id": "Invoice 1",
  "date": "12 Jan",
  "customerId": "321",
  "terms": "Terms",
  "subtotal": "Billable 1",
  "tax": "Billable Tax 1",
  "taxTotal": "Billable Tax Total 1",
  "total": "Billable Total 1",
  "billableItems": [
    {
      "description": "Billable 1",
      "quantity": "Billable Tax 1",
      "unitPrice": "Billable Tax Total 1",
      "amount": "Billable Total 1"
    },
    {
      "description": "Billable 2",
      "quantity": "Billable Tax 2",
      "unitPrice": "Billable Tax Total 2",
      "amount": "Billable Total 2"
    }
  ]
}
