=== Open-Attestation/schemas/src/sg/gov/tech/geekout/1.0/schema.json
{
  "$id": "https://schemata.openattestation.com/sg/gov/tech/geekout/1.0",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "signatory": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "position": {
          "type": "string"
        },
        "organisation": {
          "type": "string"
        },
        "signature": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "position",
        "organisation",
        "signature"
      ]
    },
    "recipient": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "programme": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "startDate": {
          "type": "string"
        },
        "endDate": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "startDate",
        "endDate"
      ]
    },
    "$template": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "type",
        "url"
      ]
    }
  },
  "required": [
    "name",
    "signatory",
    "programme",
    "recipient",
    "$template"
  ]
}

=== Open-Attestation/schemas/src/sg/gov/tech/geekout/1.0/sample-document.json
{
  "name": "GeekOut2020",
  "recipient": {
    "name": "Matthea Loo"
  },
  "programme": {
    "name": "GeekOut 2020",
    "startDate": "12-Oct-20",
    "endDate": "14-Oct-20"
  },
  "signatory": {
    "name": "Alice",
    "position": "Boss",
    "organisation": "ABC",
    "signature": "signature"
  },
  "$template": {
    "name": "GEEK_OUT_2020",
    "type": "EMBEDDED_RENDERER",
    "url": "http://localhost:3000"
  }
}
