=== Open-Attestation/schemas/src/io/tradetrust/certificate-of-origin/1.0/schema.json
{
  "$id": "https://schemata.openattestation.com/io/tradetrust/certificate-of-origin/1.0",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "Description of data expected for certificate of origin documents",
  "required": [
    "supplyChainConsignment",
    "name",
    "firstSignatoryAuthentication",
    "secondSignatoryAuthentication",
    "issueLocation",
    "issuer",
    "status",
    "isPreferential",
    "freeTradeAgreement"
  ],
  "properties": {
    "supplyChainConsignment": {
      "type": "object",
      "properties": {
        "iD": {
          "type": "string"
        },
        "information": {
          "type": "string"
        },
        "exportCountry": {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            }
          }
        },
        "exporter": {
          "type": "object",
          "properties": {
            "iD": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "postalAddress": {
              "type": "object",
              "properties": {
                "line1": {
                  "type": "string"
                },
                "line2": {
                  "type": "string"
                },
                "cityName": {
                  "type": "string"
                },
                "postcode": {
                  "type": "string"
                },
                "countrySubDivisionName": {
                  "type": "string"
                },
                "countryCode": {
                  "type": "string"
                }
              }
            }
          }
        },
        "importCountry": {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            }
          }
        },
        "importer": {
          "type": "object",
          "properties": {
            "iD": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "postalAddress": {
              "type": "object",
              "properties": {
                "line1": {
                  "type": "string"
                },
                "line2": {
                  "type": "string"
                },
                "cityName": {
                  "type": "string"
                },
                "postcode": {
                  "type": "string"
                },
                "countrySubDivisionName": {
                  "type": "string"
                },
                "countryCode": {
                  "type": "string"
                }
              }
            }
          }
        },
        "includedConsignmentItems": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "iD": {
                "type": "string"
              },
              "information": {
                "type": "string"
              },
              "crossBorderRegulatoryProcedure": {
                "type": "object",
                "properties": {
                  "originCriteriaText": {
                    "type": "string"
                  }
                }
              },
              "manufacturer": {
                "type": "object",
                "properties": {
                  "iD": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "postalAddress": {
                    "type": "object",
                    "properties": {
                      "line1": {
                        "type": "string"
                      },
                      "line2": {
                        "type": "string"
                      },
                      "cityName": {
                        "type": "string"
                      },
                      "postcode": {
                        "type": "string"
                      },
                      "countrySubDivisionName": {
                        "type": "string"
                      },
                      "countryCode": {
                        "type": "string"
                      }
                    }
                  }
                }
              },
              "tradeLineItems": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "sequenceNumber": {
                      "type": "integer"
                    },
                    "invoiceReference": {
                      "type": "object",
                      "properties": {
                        "iD": {
                          "type": "string"
                        },
                        "formattedIssueDateTime": {
                          "type": "string"
                        },
                        "attachedBinaryFile": {
                          "type": "object",
                          "properties": {
                            "uRI": {
                              "type": "string"
                            }
                          }
                        }
                      }
                    },
                    "tradeProduct": {
                      "type": "object",
                      "properties": {
                        "iD": {
                          "type": "string"
                        },
                        "description": {
                          "type": "string"
                        },
                        "harmonisedTariffCode": {
                          "type": "object",
                          "properties": {
                            "classCode": {
                              "type": "string"
                            },
                            "className": {
                              "type": "string"
                            }
                          }
                        },
                        "originCountry": {
                          "type": "object",
                          "properties": {
                            "code": {
                              "type": "string"
                            }
                          }
                        }
                      }
                    },
                    "transportPackages": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "iD": {
                            "type": "string"
                          },
                          "grossVolume": {
                            "type": "string"
                          },
                          "grossWeight": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "loadingBaseportLocation": {
          "type": "object",
          "properties": {
            "iD": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          }
        },
        "mainCarriageTransportMovement": {
          "type": "object",
          "properties": {
            "iD": {
              "type": "string"
            },
            "information": {
              "type": "string"
            },
            "usedTransportMeans": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "iD": {
                  "type": "string"
                }
              }
            },
            "departureEvent": {
              "type": "object",
              "properties": {
                "departureDateTime": {
                  "type": "string"
                }
              }
            }
          }
        },
        "unloadingBaseportLocation": {
          "type": "object",
          "properties": {
            "iD": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          }
        }
      }
    },
    "name": {
      "type": "string",
      "description": "Certificate of Origin name",
      "examples": ["CHAFTA Certificate of Origin"]
    },
    "firstSignatoryAuthentication": {
      "type": "object",
      "properties": {
        "signature": {
          "type": "string"
        },
        "actualDateTime": {
          "type": "string"
        },
        "statement": {
          "type": "string"
        }
      }
    },
    "secondSignatoryAuthentication": {
      "type": "object",
      "properties": {
        "signature": {
          "type": "string"
        },
        "actualDateTime": {
          "type": "string"
        },
        "statement": {
          "type": "string"
        }
      }
    },
    "issueLocation": {
      "iD": {
        "type": "string"
      },
      "name": {
        "type": "string"
      }
    },
    "issuer": {
      "iD": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "postalAddress": {
        "type": "object",
        "properties": {
          "line1": {
            "type": "string"
          },
          "line2": {
            "type": "string"
          },
          "cityName": {
            "type": "string"
          },
          "postcode": {
            "type": "string"
          },
          "countrySubDivisionName": {
            "type": "string"
          },
          "countryCode": {
            "type": "string"
          }
        }
      }
    },
    "status": {
      "type": "string"
    },
    "isPreferential": {
      "type": "boolean"
    },
    "freeTradeAgreement": {
      "type": "string"
    }
  }
}

=== Open-Attestation/schemas/src/io/tradetrust/certificate-of-origin/1.0/certificate-of-origin-wrapped.json
{
  "supplyChainConsignment": {
    "exportCountry": {},
    "exporter": {
      "postalAddress": {}
    },
    "importCountry": {},
    "importer": {
      "postalAddress": {}
    },
    "loadingBaseportLocation": {},
    "mainCarriageTransportMovement": {
      "usedTransportMeans": {},
      "departureEvent": {}
    },
    "unloadingBaseportLocation": {}
  },
  "name": "CHAFTA Certificate of Origin",
  "firstSignatoryAuthentication": {
    "signature": "Signature",
    "actualDateTime": "2020-05-29T09:46:34Z",
    "statement": "The undersigned hereby declares that the above-stated information is correct and that the goods exported to [importer] comply with the origin requirements specified in the China-Australia Free Trade Agreement."
  },
  "secondSignatoryAuthentication": {
    "signature": "Signature",
    "actualDateTime": "2020-06-03T03:50:45Z",
    "statement": "On the basis of the control carried out, it is hereby certified that the information herein is correct and that the described goods comply with the origin requirements of the China-Australia Free Trade Agreement."
  },
  "issueLocation": {
    "iD": "unece.un.org:locode:AUADL",
    "name": "Adelaide"
  },
  "issuer": {
    "iD": "id:wfa.org.au",
    "name": "Australian Grape and Wine Incorporated",
    "postalAddress": {
      "line1": "Level 1, Industry Offcies",
      "line2": "Botanic Road",
      "cityName": "Adelaide",
      "postcode": "5000",
      "countrySubDivisionName": "SA",
      "countryCode": "AU"
    }
  },
  "status": "issued",
  "isPreferential": true,
  "freeTradeAgreement": "CHAFTA"
}
